# Generated by Django 5.2.4 on 2025-09-04 14:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAPIPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('urlToImage', models.CharField(max_length=500)),
                ('urlToPost', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, unique=True)),
                ('description', models.TextField()),
                ('summary', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sumário')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('category', models.CharField(max_length=100)),
                ('url_to_image', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
