# Generated by Django 5.2.4 on 2025-08-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapipost',
            name='description',
            field=models.TextField(default='nenhuma descrição ainda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='nenhuma descrição ainda'),
            preserve_default=False,
        ),
    ]
