# Generated by Django 5.2.4 on 2025-09-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_newsapipost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapipost',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_to_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
