# Generated by Django 5.2.4 on 2025-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_newsapipost_title_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapipost',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
